In [1]:
pip install pandas seaborn openpyxl

Requirement already satisfied: pandas in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (2.3.3)
Requirement already satisfied: seaborn in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (0.13.2)
Requirement already satisfied: openpyxl in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from seaborn) (3.10.6)
Requirement already satisfied: et-xmlfile in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\k4484\anaconda3\envs\proectnayshkola\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import pandas as pd

df = pd.read_excel(r'C:\Users\k4484\itmo\itmo\proectnay_shkola\yandex_maps_review.xlsx')

In [17]:
df.tail(10)

,address,name_ru,rating,rubrics,text
499990,"Москва, улица Юных Ленинцев, 52",Petruccio. Pizza&Pasta,1.0,Ресторан;Кафе;Пиццерия,Сегодня заказали у вас доставку. Перепутали на...
499991,"Москва, Южный административный округ, район Би...",Бирюлёво-Пассажирская,3.0,Железнодорожная станция,В зимнее время совершенно не убирается подземн...
499992,"Москва, Южный административный округ, район Би...",Бирюлёво-Пассажирская,5.0,Железнодорожная станция,Редко бываю здесь. В основном проездом в г. Ви...
499993,"Москва, Южный административный округ, район Би...",Бирюлёво-Пассажирская,5.0,Железнодорожная станция,Отличный пересадочный узел.
499994,"Москва, Южный административный округ, район Би...",Бирюлёво-Пассажирская,5.0,Железнодорожная станция,Хороший способ избежать автобусной пытки. Элек...
499995,"Москва, Южный административный округ, район Би...",Бирюлёво-Пассажирская,4.0,Железнодорожная станция,"Охрана кривая но добрая, двери не закрываются ..."
499996,"Москва, Южный административный округ, район Би...",Бирюлёво-Пассажирская,4.0,Железнодорожная станция,По сравнению со многими современными платформа...
499997,"Новосибирск, Коммунистическая улица, 48А",NaN,5.0,"Бар, паб","Приятная атмосфера, прекрасное вино, волшебная..."
499998,"Астраханская область, Харабалинский район",Сарай-Бату,5.0,Достопримечательность,Был с семьёй 13.06.23 Отличное место. Рекоменд...
499999,"Астраханская область, Харабалинский район",Сарай-Бату,5.0,Достопримечательность,"Отличные декорации... Вблизи тяп-ляп,а на фото..."

In [20]:
df_1 = df[['rating', 'text']]
df_1.rename(columns={'text':'comment'})

        rating                                            comment
0          3.0  Московский квартал 2.\nШумно : летом по ночам ...
1          5.0  Замечательная сеть магазинов в общем, хороший ...
2          1.0  Не знаю смутят ли кого-то данные правила, но я...
3          4.0  Хорошие условия аренды. \nДружелюбный персонал...
4          5.0  Топ мастер Ангелина топ во всех смыслах ) Немн...
...        ...                                                ...
499995     4.0  Охрана кривая но добрая, двери не закрываются ...
499996     4.0  По сравнению со многими современными платформа...
499997     5.0  Приятная атмосфера, прекрасное вино, волшебная...
499998     5.0  Был с семьёй 13.06.23 Отличное место. Рекоменд...
499999     5.0  Отличные декорации... Вблизи тяп-ляп,а на фото...

[500000 rows x 2 columns]

In [21]:
df.describe()

             rating
count  500000.00000
mean        4.48160
std         1.14625
min         0.00000
25%         5.00000
50%         5.00000
75%         5.00000
max         5.00000